# Generated by Django 4.0 on 2022-03-17 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_tipo_dispositivo',
            fields=[
                ('asuntotratar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.asuntotratar')),
                ('tipo_dispositivo', models.PositiveSmallIntegerField(unique=True, verbose_name='Tipo de dispositivo')),
            ],
            bases=('usuario.asuntotratar',),
        ),
        migrations.CreateModel(
            name='dispositivos',
            fields=[
                ('asuntotratar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.asuntotratar')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_dispositivos', to='dipositivo.cat_tipo_dispositivo')),
                ('usuariosEncargados', models.ManyToManyField(related_name='get_dispositivosQueVigila', to='usuario.usuarios')),
            ],
            bases=('usuario.asuntotratar',),
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('asuntotratar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.asuntotratar')),
                ('descripccion', models.TextField(verbose_name='Descripccion: ')),
                ('send_email', models.BooleanField(verbose_name='¿Ya se mando el email de reporte?')),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_ticketsAsignados', to='dipositivo.dispositivos', verbose_name='Selecciona el dispositivo:')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_ticketsHechos', to='usuario.usuarios')),
            ],
            bases=('usuario.asuntotratar',),
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('asuntotratar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.asuntotratar')),
                ('comentario', models.TextField(verbose_name='Comentario: ')),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_comentariosAportados', to='dipositivo.ticket', verbose_name='Selecciona el ticket que deseas atender: ')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_comentariosHechos', to='usuario.usuarios', verbose_name='¿Que persona realiza el comentario?')),
            ],
            bases=('usuario.asuntotratar',),
        ),
    ]
