# Generated by Django 3.2.9 on 2022-03-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20220317_0700'),
        ('dipositivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_tipo_dispositivo',
            name='descripccion',
            field=models.TextField(blank=True, default='', verbose_name='Descripccion'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del dispositivo'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='id_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_comentariosAportados', to='dipositivo.ticket', verbose_name='Ticket que se atiende'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_comentariosHechos', to='usuario.usuarios', verbose_name='Persona que realiza el comentario'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_dispositivos', to='dipositivo.cat_tipo_dispositivo', verbose_name='Tipo de dispositivo'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_ticketsAsignados', to='dipositivo.dispositivos', verbose_name='Dispositivo:'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_ticketsHechos', to='usuario.usuarios', verbose_name='Creador del ticket'),
        ),
    ]
