# Generated by Django 4.0 on 2022-03-17 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsuntoTratar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(verbose_name='¿Esta activo?')),
            ],
        ),
        migrations.CreateModel(
            name='cat_tipo_usuario',
            fields=[
                ('asuntotratar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.asuntotratar')),
                ('tipo_usuario', models.PositiveSmallIntegerField(unique=True, verbose_name='Tipo de usuario')),
            ],
            bases=('usuario.asuntotratar',),
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('asuntotratar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.asuntotratar')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del usuario:')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo electronico')),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_usuariosConEsteTipo', to='usuario.cat_tipo_usuario', verbose_name='Selecciona el tipo de usuario:')),
            ],
            bases=('usuario.asuntotratar',),
        ),
    ]
