# Generated by Django 3.2.9 on 2022-03-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_tipo_usuario',
            name='descripccion',
            field=models.TextField(blank=True, default='', verbose_name='Descripccion'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_usuariosConEsteTipo', to='usuario.cat_tipo_usuario', verbose_name='Tipo de usuario:'),
        ),
    ]
